ci: skip formatting check for pull requests

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -1,8 +1,5 @@
 name: Check
 on:
-  push:
-    branches:
-      - master
   pull_request:
     branches:
       - master
@@ -34,8 +31,15 @@ jobs:
       - name: Install dependencies
         run: pnpm install
 
-      - name: Check
-        run: pnpm check
+      - name: Check by Biome
+        run: pnpm biome ci --formatter-enabled=false --reporter=github
+
+      - name: Check by Prettier
+        # Allow formatting issues (exit code 1) but fail on syntax errors (exit code 2).
+        run: pnpm prettier --check '**/*.{html,yml,yaml,md}' || (( $? == 1 ))
+
+      - name: Check by TypeScript
+        run: pnpm tsc --build
 
       - name: Test
         run: pnpm test
@@ -50,9 +54,3 @@ jobs:
           DROPBOX_API_SECRET: ${{ secrets.DROPBOX_API_SECRET }}
           GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
           GOOGLE_DRIVE_API_SECRET: ${{ secrets.GOOGLE_DRIVE_API_SECRET }}
-
-      - name: Upload build artifacts
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
-        with:
-          name: dist
-          path: dist
